### ISSUE TITLE
Failed settlement simulation logs use incorrect solver name.

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#844] opened 2021-07-12 17:07 UTC
I'm not sure the exact cause of the issue, but it appears that there are situations where the simulation failure log will use a solver name that does not match settlement data in the error `context`. Note that the simulation call data appears to be correct.

<details><summary>Sample log:</summary>

```
2021-07-10T04:11:48.369Z ERROR solver::driver: Matcha settlement simulation failed at submission and block 12797442:
https://dashboard.tenderly.co/gp-v2/staging/simulator/new?block=12797442&blockIndex=0&from=0xa6ddbd0de6b310819b49f680f65871bee85f517e&gas=8000000&gasPrice=0&value=0&contractAddress=0x3328f5f2cecaf00a2443082b657cedeaf70bfaef&network=1&rawFunctionInput=0x13d79a0b00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000003a00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000dada00a9c23390112d08a1377cc59f7d03d9df55000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000187a12f22d01e45cad850000000000000000000000000000000000000000000000000000000003c22340f629bb5c000000000000000000000000000000000000187a12f22d01e45cad85000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000941387bdc60144b7bfa4db788ce87f58428b5d1a000000000000000000000000000000000000187a12f22d01e45cad850000000000000000000000000000000000000000000000000000000002af3dc0afd4aa6c0000000000000000000000000000000000000000000000000000000060e91e460000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000002cd03019c7b8040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000187a12f22d01e45cad85000000000000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000004122cd1a5892528cf38fa197f6b3fecfded1032419ec2472f794e84e8840fdbc4e483df64a8cf9c2e8977e4e54379ee7e45b177a7c50ad4275bfb961d4ffb50fb81c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000046000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000300000000000000000000000000dada00a9c23390112d08a1377cc59f7d03d9df55000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000def1c0ded9bec7f1a1670819833240f027b25effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000def1c0ded9bec7f1a1670819833240f027b25eff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000128d9627aa40000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000187a12f22d01e45cad850000000000000000000000000000000000000000000000000000000003c1a819a2126a3d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000dada00a9c23390112d08a1377cc59f7d03d9df55000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2869584cd000000000000000000000000100000000000000000000000000000000000001100000000000000000000000000000000000000000000005d566acd1560e91e04000000000000000000000000000000000000000000000000000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000242e1a7d4d00000000000000000000000000000000000000000000000003c22340f629bb5c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Caused by:
    0: method 'settle(address[],uint256[],(uint256,uint256,address,uint256,uint256,uint32,bytes32,uint256,uint256,uint256,bytes)[],(address,uint256,bytes)[][3])' failure: contract call reverted with message: Some("UniswapV2: OVERFLOW")
    1: contract call reverted with message: Some("UniswapV2: OVERFLOW")
    settlement: Settlement {
        encoder: SettlementEncoder {
            tokens: [
                0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,
                0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,
            ],
            clearing_prices: {
                0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2: 1000000000000000000,
                0xdada00a9c23390112d08a1377cc59f7d03d9df55: 546,
                0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee: 1000000000000000000,
            },
            trades: [
                Trade {
                    order: Order {
                        order_meta_data: OrderMetaData {
                            creation_date: 2021-07-10T03:12:57.660987Z,
                            owner: 0x941387bdc60144b7bfa4db788ce87f58428b5d1a,
                            uid: 0xcf7025c25b52ec6402f22387604be75ad09a05cac43113720f04e4654387737a941387bdc60144b7bfa4db788ce87f58428b5d1a60e91e46,
                            available_balance: Some(
                                500000000000000000000000000000000,
                            ),
                            executed_buy_amount: BigUint {
                                data: [],
                            },
                            executed_sell_amount: BigUint {
                                data: [],
                            },
                            executed_sell_amount_before_fees: BigUint {
                                data: [],
                            },
                            executed_fee_amount: BigUint {
                                data: [],
                            },
                            invalidated: false,
                            status: Open,
                        },
                        order_creation: OrderCreation {
                            sell_token: 0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                            buy_token: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,
                            receiver: Some(
                                0x941387bdc60144b7bfa4db788ce87f58428b5d1a,
                            ),
                            sell_amount: 496449529817146864003776709132288,
                            buy_amount: 193441206793185900,
                            valid_to: 1625890374,
                            app_data: [
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                1,
                            ],
                            fee_amount: 3550470182853135996223290867712,
                            kind: Sell,
                            partially_fillable: false,
                            signature: Signature {
                                r: 0x22cd1a5892528cf38fa197f6b3fecfded1032419ec2472f794e84e8840fdbc4e,
                                s: 0x483df64a8cf9c2e8977e4e54379ee7e45b177a7c50ad4275bfb961d4ffb50fb8,
                                v: 28,
                            },
                            signing_scheme: Eip712,
                        },
                    },
                    sell_token_index: 1,
                    buy_token_index: 2,
                    executed_amount: 496449529817146864003776709132288,
                },
            ],
            execution_plan: [
                Approve {
                    token: 0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                    spender: 0xd9e1ce17f2641f24ae83637ab66a2cca9c378b9f,
                },
                UniswapInteraction {
                    router: IUniswapLikeRouter(
                        0xd9e1ce17f2641f24ae83637ab66a2cca9c378b9f,
                    ),
                    settlement: GPv2Settlement(
                        0x3328f5f2cecaf00a2443082b657cedeaf70bfaef,
                    ),
                    amount_out: 270817689510460313,
                    amount_in_max: 496945979346964026765393956238055,
                    token_in: 0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                    token_out: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,
                },
            ],
            unwraps: [
                UnwrapWethInteraction {
                    weth: WETH9(
                        0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,
                    ),
                    amount: 271061443280162187,
                },
            ],
        },
    },
}
```

</details>

In this log, the driver is reporting that a Matcha settlement simulation failed, but it appears to be using a Baseline/Naive solver settlement as part of the context for the error (notice that it uses a `UniswapInteraction` which is not possible for the Matcha solver instead of a `SwapResponse` which is the only interaction the Matcha solver encodes).

For reference, here is the Matcha settlement:
<details><summary>Matcha settlement:</summary>

```
2021-07-10T04:11:48.369Z  WARN solver::driver: settlement failure for: 
SettlementWithSolver {
    name: "Matcha",
    settlement: Settlement {
        encoder: SettlementEncoder {
            tokens: [
                0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,
                0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,
            ],
            clearing_prices: {
                0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2: 496449529817146864003776709132288,
                0xdada00a9c23390112d08a1377cc59f7d03d9df55: 270817689510460252,
                0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee: 496449529817146864003776709132288,
            },
            trades: [
                Trade {
                    order: Order {
                        order_meta_data: OrderMetaData {
                            creation_date: 2021-07-10T03:12:57.660987Z,
                            owner: 0x941387bdc60144b7bfa4db788ce87f58428b5d1a,
                            uid: 0xcf7025c25b52ec6402f22387604be75ad09a05cac43113720f04e4654387737a941387bdc60144b7bfa4db788ce87f58428b5d1a60e91e46,
                            available_balance: Some(
                                500000000000000000000000000000000,
                            ),
                            executed_buy_amount: BigUint {
                                data: [],
                            },
                            executed_sell_amount: BigUint {
                                data: [],
                            },
                            executed_sell_amount_before_fees: BigUint {
                                data: [],
                            },
                            executed_fee_amount: BigUint {
                                data: [],
                            },
                            invalidated: false,
                            status: Open,
                        },
                        order_creation: OrderCreation {
                            sell_token: 0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                            buy_token: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,
                            receiver: Some(
                                0x941387bdc60144b7bfa4db788ce87f58428b5d1a,
                            ),
                            sell_amount: 496449529817146864003776709132288,
                            buy_amount: 193441206793185900,
                            valid_to: 1625890374,
                            app_data: [
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                1,
                            ],
                            fee_amount: 3550470182853135996223290867712,
                            kind: Sell,
                            partially_fillable: false,
                            signature: Signature {
                                r: 0x22cd1a5892528cf38fa197f6b3fecfded1032419ec2472f794e84e8840fdbc4e,
                                s: 0x483df64a8cf9c2e8977e4e54379ee7e45b177a7c50ad4275bfb961d4ffb50fb8,
                                v: 28,
                            },
                            signing_scheme: Eip712,
                        },
                    },
                    sell_token_index: 1,
                    buy_token_index: 2,
                    executed_amount: 496449529817146864003776709132288,
                },
            ],
            execution_plan: [
                Approve {
                    token: 0xdada00a9c23390112d08a1377cc59f7d03d9df55,
                    spender: 0xdef1c0ded9bec7f1a1670819833240f027b25eff,
                },
                SwapResponse {
                    sell_amount: 496449529817146864003776709132288,
                    buy_amount: 270817689510460252,
                    allowance_target: 0xdef1c0ded9bec7f1a1670819833240f027b25eff,
                    price: 0.000000000000000545,
                    to: 0xdef1c0ded9bec7f1a1670819833240f027b25eff,
                    data: 0xd9627aa40000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000187a12f22d01e45cad850000000000000000000000000000000000000000000000000000000003c1a819a2126a3d00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000dada00a9c23390112d08a1377cc59f7d03d9df55000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2869584cd000000000000000000000000100000000000000000000000000000000000001100000000000000000000000000000000000000000000005d566acd1560e91e04,
                    value: 0,
                },
            ],
            unwraps: [
                UnwrapWethInteraction {
                    weth: WETH9(
                        0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,
                    ),
                    amount: 270817689510460252,
                },
            ],
        },
    },
}
```

</details>

**Comment by bh2smith** [comment] 2021-07-12 18:06
I would think this is something that @josojo might have some initial intuition for.

**Comment by fleupold** [comment] 2021-07-13 13:53
I don't think this is specific to the Match solver and instead a mingling issue with out logging library. Note, that normally for logs of kind `settlement simulation failed at submission and block x` we only see the revert reason (not the full settlement, e.g. https://logs.gnosis.io/app/kibana#/discover/doc/7ea8a550-5471-11e9-98b4-3b011d27ba56/logstash-2021.07.10?id=feadjnoBvC3o9g71Upd5)

The settlement info we see in this log seems to be partially copied from a different log entry that indeed belongs to the baseline solver: https://logs.gnosis.io/app/kibana#/discover/doc/7ea8a550-5471-11e9-98b4-3b011d27ba56/logstash-2021.07.10?id=e-adjnoBvC3o9g71Upd5

I'm not sure this is worth investigating

**Comment by vkgnosis** [comment] 2021-07-13 14:09
I believe this is kibana and not the logging library btw. I investigated these kind of mixed up lines before and couldn't reproduce it locally.

**Comment by bh2smith** [comment] 2021-07-13 14:15
I will close this for now, just to keep things tidy. Feel free to reopen as necessary.

**Closed by bh2smith** 2021-07-13 14:15 UTC
Labels: bug, oncall
