### ISSUE TITLE
Include Balancer Pools in Price Estimation Service

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#1075] opened 2021-09-03 07:08 UTC
As a final step to #733. Currently we do not pass Balancer Liquidity on to the price estimation service. This issue is to adapt price_estimate to include these sources.

**Comment by bh2smith** [comment] 2021-12-17 10:57
Outdated due to recent refactor.

**Comment by nlordell** [comment] 2021-12-17 11:24
Unfortunately this is still true. 

I'll leave this closed as this is a duplciate of: https://github.com/gnosis/gp-v2-services/issues/1412

**Comment by vkgnosis** [comment] 2022-01-05 12:06
I consider this not so important because we are probably moving towards Quasimodo price estimates. Maybe in the process of implementing that we will also make progress here but not sure if we should invest extra work.

**Comment by nlordell** [comment] 2022-01-05 12:24
The issue is that Quasimodo has very limited liquidity to work with for price estimates. But as you said, the plan is to make progress with this with trade simulations for more accurate gas estimates.

**Closed** 2022-04-07 13:32 UTC
Labels: balancer-integration
