### ISSUE TITLE
Pruned orders - user experience

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#1351] opened 2021-11-05 07:01 UTC
Currently, we are pruning some orders, if we don't have price estimations for the tokens. We need the price estimations in the current process to evaluate the token-surplus in the settlement evaluations.

Here is one concrete instance, where a user order was just pruned, and the user never gets any feedback why the settlement would not go through.
https://gnosisinc.slack.com/archives/C020UHS2UEL/p1636015696067500

Let's use this thread to discuss potential solutions.

1. proposed solution:
Deny orders for un-index liquidity: This gives at least the user an immediate feedback. But I don't like it as we loose potential customers

2. proposed solution
Get the price estimates via another source, i.e. 0x, paraswap. My preferred solution.

**Comment by fleupold** [comment] 2021-11-05 09:09
> Get the price estimates via another source, i.e. 0x, paraswap. My preferred solution.

Agree that this is nicer instead of restricting trading. At the moment I'm a bit worried about the load this would cause.

One hacky idea that I had was that in case of only having a single order, we can estimate the price of the token from the limit price (+ some hardcoded assumed slippage). Since this value is only used to assess solution quality, the estimate shouldn't matter too much for single order batches.

**Comment by fleupold** [comment] 2021-11-05 16:37
Fixing this would add support for LBPs as requested by https://gnosisinc.slack.com/archives/C01MZ4QD763/p1636124274036300

**Comment by fleupold** [comment] 2021-11-18 13:55
Duplicate of #1253

**Closed by fleupold** 2021-11-18 13:55 UTC
